### ISSUE TITLE
KUB another solution

### ISSUE THREAD

**Issue by fagci** [gil9red/SimplePyScripts#13]
https://github.com/gil9red/SimplePyScripts/blob/154b0f877e6b5920095f21642a403f9a6dceede3/(K%2BU%2BB)%5E3%3DKUB.py#L16

```py
for num in range(100, 1000):
    kub = set(str(num))
    if len(kub) == 3 and sum(map(int, kub))**3 == num:
        print(f'({"+".join(kub)})^3 = {num}')
```

**Comment by gil9red** [comment]
@fagci, спасибо за замечания, подправил :)
Кст, если придираться, то можно прийти к таком условию перебора:
```
for num in range(102, 987+1):
```
Ведь цифры в K, U, B должны быть разные, поэтому начинаться с 100 и заканчиваться на 999 точно не может :D

**Comment by gil9red** [comment]
c1e4af724e46219f633367dd33e5542925f206b4
