### ISSUE TITLE
Присвоено неверное авторство

### ISSUE THREAD

**Issue by fagci** [gil9red/SimplePyScripts#14]
Здесь автором должен быть `fagci`:

https://github.com/gil9red/SimplePyScripts/blob/c1e4af724e46219f633367dd33e5542925f206b4/(K%2BU%2BB)%5E3%3DKUB%20v2.py#L4

На основании сообщения с исходником:

https://github.com/gil9red/SimplePyScripts/issues/13#issuecomment-943412289

**Comment by gil9red** [comment]
@fagci, `__author__` создается автоматически и я подразумеваю этим автора файла, того кто его создал (т.е. себя)

А ниже в `# SOURCE: ` указываю место откуда взят код, в данном случае это:
https://github.com/gil9red/SimplePyScripts/blob/c1e4af724e46219f633367dd33e5542925f206b4/(K%2BU%2BB)%5E3%3DKUB%20v2.py#L4-L7

По ссылке и будет ваш комментарий с кодом

А вообще, может быть и несколько источников:
https://github.com/gil9red/SimplePyScripts/blob/e70eed0f3374eba2fb23a0946a9fef35eb302c61/flask__webservers/bootstrap_4__toggle_switch__examples/main.py#L6-L10
