### ISSUE TITLE
please stop scraping websniffer.com

### ISSUE THREAD

**Issue by websniffercom** [gil9red/SimplePyScripts#23]
Hi,

We would like to kindly request the removal of our site, websniffer.com, from your [redirect scraping script](https://github.com/gil9red/SimplePyScripts/blob/ff05341e92d8a5e6db91385dd77e480aa1fc0846/html_parsing/websniffer_com__get_redirected_url.py). It can create additional and unintended load on our servers if used extensively.

Thanks in advance.

**Comment by gil9red** [comment]
Hi!
Have you heard about the Streisand effect? ;)

Okay, I'll remove the script from the repository :)

**Comment by gil9red** [comment]
https://github.com/gil9red/SimplePyScripts/commit/9cc04c96487a8c21c7ef8f8f857921d1cf769e6e

**Comment by websniffercom** [comment]
Thanks for the quick fix! Just out of curiosity, why use an intermediary site to track the destination of a redirect if it can be done directly in Python, without any intermediaries? This can be achieved using the `requests` library, which allows handling of HTTP requests and responses directly. To track redirections, you can disable automatic redirection handling in `requests` and inspect the response headers manually to determine the redirected URL.

Here is a simplified version of your script that directly tracks the URL redirection without the need for an intermediary website:

```python
import requests

def get_redirected_url(url_from: str) -> str:
    # Disable automatic redirection
    session = requests.Session()
    session.headers['User-Agent'] = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0"
    response = session.get(url_from, allow_redirects=False)

    if response.status_code in (301, 302, 303, 307, 308):
        # This is the redirected URL
        return response.headers['Location']

    # If there's no redirection or it's not a redirect status code, return the original URL
    return url_from

if __name__ == "__main__":
    url_from = "http://example.com"
    redirected_url = get_redirected_url(url_from)
    print(redirected_url)
```

**Comment by gil9red** [comment]
@websniffercom, you're right! :)
But I tested the idea of ​​using your site as a proxy

Therefore, type was HEAD (and not GET), because was not interested in the content of the page
