### ISSUE TITLE
Propose logo 

### ISSUE THREAD

**Issue by dee-y** [gil9red/SimplePyScripts#3]
Hello, i am a graphic designer and i would like to contribute a logo to your project. It's free of course if you want it

**Comment by gil9red** [comment]
Hello!
Do you want to add it to README.md?
I would be interested to look at that logo :)

**Comment by dee-y** [comment]
Yes. Owk i will have a logo or two for you to look at soon.

**Comment by gil9red** [comment]
Cool :)

**Comment by dee-y** [comment]
Hi there, i have made these designs, what do you think? do you have any improvements?
![pyscript-01](https://user-images.githubusercontent.com/36637989/46838639-1b424200-cdb2-11e8-9e22-2daf70e86c1b.png)

**Comment by gil9red** [comment]
Cool! I like everything :)
Can you only change PyScript -> PyScripts?

**Comment by dee-y** [comment]
Alright i have made changes below. :) is there any particular one you favorite? So i can export the transparent HD images for you as well as the editable files.
![pyscript-01](https://user-images.githubusercontent.com/36637989/46882230-d4059100-ce45-11e8-9093-30b860779eb9.png)

**Comment by gil9red** [comment]
I liked everything :)
And it was a difficult choice ...

![default](https://user-images.githubusercontent.com/6244078/46885772-67ed5200-ce72-11e8-8672-4cd3b2d15c5e.png)

If you do not mind, I would like to add it to README.md :)
With indicating your authorship, of course :)

**Comment by dee-y** [comment]
Sure you can go ahead. Will have the HD versions for you soon

**Comment by dee-y** [comment]
Alright i have successfully uploaded HD files for you at google drive link. Logomark, logotype and single color versions of logo can be found in folders, as well as licence for logo use. 

https://drive.google.com/drive/folders/1-ItaIFZPNEyM-osPyTtfcEi0yR__Q3tT?usp=sharing

cheers.

**Comment by gil9red** [comment]
@dee-y , thank you very much for the logo! :)

**Comment by dee-y** [comment]
The pleasure is mine :)
